### ISSUE TITLE
 Parse Error: <multiselect :options="allGroups"

### ISSUE THREAD

**Issue by lidashuang** [monterail/vue-multiselect#106]
webpack 1.13.2
vue-multiselect 1.1.2

code

        <div class="columns">
          <div class="column is-4">
            <multiselect
              :options="allGroups",
              :close-on-select="true",
              :custom-label="styleLabel",
              @update="updateGroupSelected",
              placeholder="活动组",
              label="name",
              key="name",
            </multiselect>
          </div>
          <div class="column">
             <multiselect
              :options="groupInstances",
              :close-on-select="true",
              :custom-label="instanceStyleLabel",
              @update="updateInstanceSelected",
              placeholder="活动实例",
              label="name",
              key="name",
            </multiselect>
          </div>
         </div>

when build in production, module build failed, but dev is ok

```
ERROR in ./~/vue-html-loader!./~/vue-loader/lib/template-rewriter.js?id=_v-36767c88!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/FirstPay.vue
Module build failed: Error: Parse Error: <multiselect :options="allGroups" ,="" :close-on-select="true" :custom-label="styleLabel" @update="updateGroupSelected" placeholder="活动组" label="name" key="name" <="" multiselect="" _v-36767c88="">
        </multiselect></div>
        <div class="column" _v-36767c88="">
           <multiselect :options="groupInstances" ,="" :close-on-select="true" :custom-label="instanceStyleLabel" @update="updateInstanceSelected" placeholder="活动实例" label="name" key="name" <="" multiselect="" _v-36767c88="">
        </multiselect></div>
       </div>
       <button type="button" name="button" class="button" @click="loadConf" _v-36767c88="">加载配置</button>
       <button type="button" name="button" class="button" @click="updateConf" _v-36767c88="">更新</button>
    </div>
  </div>
</div>
    at new HTMLParser (/Users/lidashuang/code/cc_activity/node_modules/html-minifier/src/htmlparser.js:236:13)
    at minify (/Users/lidashuang/code/cc_activity/node_modules/html-minifier/src/htmlminifier.js:945:3)
    at Object.exports.minify (/Users/lidashuang/code/cc_activity/node_modules/html-minifier/src/htmlminifier.js:1294:10)
    at Object.module.exports (/Users/lidashuang/code/cc_activity/node_modules/vue-html-loader/index.js:85:26)
 @ ./app/src/components/FirstPay.vue 4:19-210
```

![image](https://cloud.githubusercontent.com/assets/612381/18504492/170879ce-7a95-11e6-8738-792193f69b0e.png)

**Comment by shentao** [comment]
Hey there! 
If you’re not using jade/pug template engine for your templates, you don’t need to use the commas `,` to separate attributes. 

```html
<multiselect
          :options="allGroups"
          :close-on-select="true"
          :custom-label="styleLabel"
          @update="updateGroupSelected"
          placeholder="活动组"
          label="name"
          key="name"
        </multiselect>
```
Should be working.

**Comment by lidashuang** [comment]
Thanks for answer
I remove commas form [code](https://github.com/lidashuang/cc_activity/blob/master/app/src/components/FirstPay.vue#L63-L83), but not work, and [webpack config](https://github.com/lidashuang/cc_activity/blob/master/webpack.config.js)

```
ERROR in ./~/vue-html-loader!./~/vue-loader/lib/template-rewriter.js?id=_v-36767c88!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/FirstPay.vue
Module build failed: Error: Parse Error: <multiselect :options="allGroups" :close-on-select="true" :custom-label="styleLabel" @update="updateGroupSelected" placeholder="活动组" label="name" key="name" <="" multiselect="" _v-36767c88="">
        </multiselect></div>
        <div class="column" _v-36767c88="">
           <multiselect :options="groupInstances" :close-on-select="true" :custom-label="instanceStyleLabel" @update="updateInstanceSelected" placeholder="活动实例" label="name" key="name" <="" multiselect="" _v-36767c88="">
        </multiselect></div>
       </div>
       <button type="button" name="button" class="button" @click="loadConf" _v-36767c88="">加载配置</button>
       <button type="button" name="button" class="button" @click="updateConf" _v-36767c88="">更新</button>
    </div>
  </div>
</div>
    at new HTMLParser (/Users/lidashuang/code/cc_activity/node_modules/html-minifier/src/htmlparser.js:236:13)
    at minify (/Users/lidashuang/code/cc_activity/node_modules/html-minifier/src/htmlminifier.js:945:3)
    at Object.exports.minify (/Users/lidashuang/code/cc_activity/node_modules/html-minifier/src/htmlminifier.js:1294:10)
    at Object.module.exports (/Users/lidashuang/code/cc_activity/node_modules/vue-html-loader/index.js:85:26)
 @ ./app/src/components/FirstPay.vue 4:19-210
```

**Comment by shentao** [comment]
You’re still missing the closing `>`.
```
<multiselect
          :options="allGroups"
          :close-on-select="true"
          :custom-label="styleLabel"
          @update="updateGroupSelected"
          placeholder="活动组"
          label="name"
          key="name">
        </multiselect>
```
Missed it myself in the code above. Should be fine now.

**Comment by lidashuang** [comment]
![image](https://cloud.githubusercontent.com/assets/612381/18505184/b6b6a272-7a98-11e6-98a0-c24bcdb731c5.png)

remove ` </multiselect`, now work, thanks

**Comment by shentao** [comment]
Happy to hear that :)
